<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class galeria extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 1','rutafotoprincipal'=>'/proyectos/proyecto_1.jpg','descripcionbreve'=>'P1.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'1'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 2','rutafotoprincipal'=>'/proyectos/proyecto_2.jpg','descripcionbreve'=>'P2.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'1'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 3','rutafotoprincipal'=>'/proyectos/proyecto_3.jpg','descripcionbreve'=>'P3.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'1'));

        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 4','rutafotoprincipal'=>'/proyectos/proyecto_4.jpg','descripcionbreve'=>'P4.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'2'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 5','rutafotoprincipal'=>'/proyectos/proyecto_5.jpg','descripcionbreve'=>'P5.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'2'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 6','rutafotoprincipal'=>'/proyectos/proyecto_6.jpg','descripcionbreve'=>'P6.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'2'));

        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 7','rutafotoprincipal'=>'/proyectos/proyecto_7.jpg','descripcionbreve'=>'P7.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'3'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 8','rutafotoprincipal'=>'/proyectos/proyecto_8.jpg','descripcionbreve'=>'P8.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'3'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 9','rutafotoprincipal'=>'/proyectos/proyecto_9.jpg','descripcionbreve'=>'P9.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'3'));

        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 10','rutafotoprincipal'=>'/proyectos/proyecto_10.jpg','descripcionbreve'=>'P10.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'4'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 11','rutafotoprincipal'=>'/proyectos/proyecto_11.jpg','descripcionbreve'=>'P11.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'4'));
        DB::table('galeria')-> insert(array('nombreproyecto'=>'Proyecto 12','rutafotoprincipal'=>'/proyectos/proyecto_12.jpg','descripcionbreve'=>'P12.- Brindamos soluciones de con aluminio confiables a nuestros clientes individuales y corporativos en todo México.','descripcionlarga'=>'Proyecto dentro del cual se desarrollaron puertas de aluminio, detalladas y grabadas, con una longitud de 2.2 metros por 1.4 mtrs, proyecto realizado en tan sólo dos días de trabajo, satisfaciendo las necesidades de nuestro cliente, etc, etc, etc','fkidmodulo'=>'4'));
    }
}
